---
title: "rmsfuns"
author: "Nico Katzke"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rmsfuns}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Introduction 

This package package contains several useful helper functions for data manipulation and viewing of dataframes.

To install this package, run:

    if (!require("devtools")) install.packages("devtools")
    library(devtools)
    devtools::install_github("Nicktz/rmsfuns")
    library(rmsfuns)

## build_path

This function builds the entire folder path provided by the user. If the path does not exist, it builds it without error. It is effectively a user-friendly wrapper to the base function dir.create.

    library(rmsfuns)
    Path <- build_path("C:/Temp/data/")
    print(Path)

Can also be used to build a vector of paths:

    library(rmsfuns)
    Path <- build_path(paste0("C:/Temp/data/", c("SubFolder1", "SubFolder2", "SubFolder3"))
    print(Path)
    
## ViewXL

This function makes it easy to quickly view any R object or dataframe in excel. A random file is created in R's temporary folder location (see tempdir() to find your location). The excel file location can also be overridden using the FilePath command. IMPORTANT: Set mac = TRUE if using a mac.

    library(rmsfuns)
    df <- data.frame(date = seq(as.Date("2012-01-01"),
                            as.Date("2015-08-18"),"day"), x = rnorm(1326, 10,2))
    ViewXL(df, mac = FALSE)

To clean the R temporary file folder (done periodically if using ViewXL often - especially with large excel files), use CleanTempFolder:

    library(rmsfuns)
    CleanTempFolder()

## dateconverter

The dateconverter function makes it easy to create a date vector in R. It offers a simple wrapper using xts functionality to create a vector of dates between a given Start and End date, and then correcting for the chosen frequency transformation.

It can do the following transformations between given Start and End Dates:

alldays ; calendarEOM ; weekdays ; weekdayEOW ; weekdayEOM ; weekdayEOQ ; weekdayEOY

    library(rmsfuns)
    dates <- dateconverter(as.Date("2000-01-01"), as.Date("2017-01-01"), "alldays") 
    dates <- dateconverter(as.Date("2000-01-01"), as.Date("2017-01-01"), "weekdays") 
    dates <- dateconverter(as.Date("2000-01-01"), as.Date("2017-01-01"), "calendarEOM")
    dates <- dateconverter(as.Date("2000-01-01"), as.Date("2017-01-01"), "weekdayEOW")
    dates <- dateconverter(as.Date("2000-01-01"), as.Date("2017-01-01"), "weekdayEOM")
    dates <- dateconverter(as.Date("2000-01-01"), as.Date("2017-01-01"), "weekdayEOQ")
    dates <- dateconverter(as.Date("2000-01-01"), as.Date("2017-01-01"), "weekdayEOY")


## PromptAsTime

To change R's prompt to reflect the time, use the PromptAsTime function. This can be used as a simple means of timing long calculations without using sys.time() commands. This can be very useful if running, e.g., many functions overnight, and later viewing the time taken on multiple calculations.

To set the timer on, type:

    PromptAsTime(TRUE)

The time for each command will now be shown in Rstudio's prompt.

To set the prompt timer off, type:

    PromptAsTime(FALSE)
    
    
## load_pkg

This function loads a vector of packages into R, and installs the package if it has not yet been installed.

    load_pkg(c("ggplot2", "dplyr"))
    
